"""Tests for the Phase 3 synthetic reasoning corpus.

The dataset is generated by a script, so the only thing standing between a
plausible-looking corpus and a worthless one is a test suite that checks the
properties the corpus is *supposed* to have. Nine of them, in the order they
would ruin the phase if violated:

1. Train and test entity pools are disjoint -- otherwise ``test_names``
   measures nothing.
2. Held-out templates never appear in a training split -- otherwise
   ``test_templates`` measures nothing.
3. No prompt appears in two splits -- otherwise every test number is inflated
   by memorisation.
4. The answer's mention position is balanced -- otherwise "always answer the
   first name" is a free pass and the accuracy is meaningless.
5. Nothing tokenises to ``<unk>`` -- an unknown token cannot be learned.
6. ``answer`` is ``candidates[answer_index]`` -- the likelihood-ranking
   evaluator depends on it.
7. Encoded examples fit the length cap.
8. Regenerating with the same seed is byte-identical -- the brief requires the
   dataset to be reproducible from the released script.
9. The labels are right, re-derived independently of the generator.

Assertion 9 is the important one. Everything else checks bookkeeping; this
checks that the ground truth is actually true, using ``order`` / ``values``
(what the generator claims the world is) and the template semantics, without
reusing the generator's own answer-selection code.

The data-dependent tests skip if the corpus has not been generated yet, so the
suite stays green on a fresh clone.
"""

from __future__ import annotations

import json
import math
import subprocess
import sys
from pathlib import Path

import pytest

from finetune.gen_reasoning import (
    HELDOUT_TEMPLATE_WEIGHTS,
    TEMPLATES,
    TRAIN_TEMPLATE_WEIGHTS,
    language_spec,
    validate_pools,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
LANGS = ["hi", "ne"]
SPLITS = ["train", "val", "test_iid", "test_names", "test_templates"]
IN_PATTERN_SPLITS = ["train", "val", "test_iid"]
MAX_LEN = 128


# --------------------------------------------------------------------------- #
# Fixtures and helpers
# --------------------------------------------------------------------------- #


def data_dir(lang: str) -> Path:
    """Where a language's generated corpus lives."""
    return REPO_ROOT / language_spec(lang).dir_name / "reasoning"


def load_split(lang: str, split: str) -> list[dict]:
    """Read one split, skipping the test if the corpus is not generated yet."""
    path = data_dir(lang) / f"{split}.jsonl"
    if not path.exists():
        pytest.skip(f"{path} not generated yet -- run finetune.gen_reasoning")
    with open(path, encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def load_tokenizer_or_skip(lang: str):
    """Load the Phase 1 tokenizer, skipping if sentencepiece or the model is absent."""
    spm = pytest.importorskip("sentencepiece")
    model = REPO_ROOT / language_spec(lang).dir_name / "tokenizer" / f"{lang}_bpe_10000.model"
    if not model.exists():
        pytest.skip(f"tokenizer not found: {model}")
    return spm.SentencePieceProcessor(model_file=str(model))


def all_names(spec, split: str) -> set[str]:
    """Every entity name in one side of the pools."""
    return {
        name
        for pool in spec.pools[split].values()
        for group in pool.values()
        for name in group
    }


# --------------------------------------------------------------------------- #
# 1. Pool disjointness and internal sanity
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("lang", LANGS)
def test_pools_validate(lang):
    """The resource tables pass their own startup checks.

    Covers pool disjointness, the substring rule that mention-order recovery
    depends on, and the minimum group size the three-entity templates need.
    """
    validate_pools(language_spec(lang))


@pytest.mark.parametrize("lang", LANGS)
def test_train_and_test_names_are_disjoint(lang):
    """Assertion 1: no entity name is shared between the two pools."""
    spec = language_spec(lang)
    assert not (all_names(spec, "train") & all_names(spec, "test"))


@pytest.mark.parametrize("lang", LANGS)
def test_generated_splits_use_the_right_pools(lang):
    """The held-out-name splits really do use only held-out names.

    Checking the pool tables is not enough: what matters is which names ended
    up in the files.
    """
    spec = language_spec(lang)
    train_names, test_names = all_names(spec, "train"), all_names(spec, "test")

    for split in IN_PATTERN_SPLITS:
        used = {name for r in load_split(lang, split) for name in r["entities"]}
        assert used <= train_names, f"{split} used held-out names: {sorted(used - train_names)}"

    for split in ("test_names", "test_templates"):
        used = {name for r in load_split(lang, split) for name in r["entities"]}
        assert used <= test_names, f"{split} used training names: {sorted(used - test_names)}"


# --------------------------------------------------------------------------- #
# 2. Template disjointness
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("lang", LANGS)
def test_held_out_templates_never_appear_in_training_splits(lang):
    """Assertion 2: T3 and T6 are absent from train, val and test_iid."""
    held_out = set(HELDOUT_TEMPLATE_WEIGHTS)
    assert held_out == {t for t, m in TEMPLATES.items() if m["role"] == "test"}

    for split in IN_PATTERN_SPLITS:
        seen = {r["template"] for r in load_split(lang, split)}
        assert not (seen & held_out), f"{split} contains held-out templates: {sorted(seen & held_out)}"
        assert seen <= set(TRAIN_TEMPLATE_WEIGHTS)

    seen = {r["template"] for r in load_split(lang, "test_templates")}
    assert seen <= held_out
    assert seen == held_out, "test_templates should exercise every held-out family"


# --------------------------------------------------------------------------- #
# 3. Prompt disjointness
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("lang", LANGS)
def test_no_prompt_appears_in_two_splits(lang):
    """Assertion 3: the splits share no prompt string."""
    prompts = {split: {r["prompt"] for r in load_split(lang, split)} for split in SPLITS}
    for i, first in enumerate(SPLITS):
        for second in SPLITS[i + 1:]:
            overlap = prompts[first] & prompts[second]
            assert not overlap, (
                f"{len(overlap)} prompt(s) shared between {first} and {second}, "
                f"e.g. {sorted(overlap)[:2]}"
            )


@pytest.mark.parametrize("lang", LANGS)
@pytest.mark.parametrize("split", ["val", "test_iid", "test_names", "test_templates"])
def test_evaluation_splits_have_no_internal_repeats(lang, split):
    """No test example is scored twice."""
    records = load_split(lang, split)
    assert len({r["prompt"] for r in records}) == len(records)


# --------------------------------------------------------------------------- #
# 4. Balance controls
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("lang", LANGS)
@pytest.mark.parametrize("split", SPLITS)
def test_answer_position_is_balanced_within_each_template(lang, split):
    """Assertion 4a: within a family, the answer is spread over the positions it can reach.

    Checked per template rather than per split because the families differ in
    how many mention positions their answer can occupy. T0 has two entities and
    therefore two positions; T6 asks for the middle of a three-entity chain, and
    that entity is named in *both* premises, so it appears first or second but
    never last -- no amount of shuffling can change that.

    So the reachable positions are read off the data and each is required to
    hold no more than ``1/k + 0.10`` of that family's answers. That is what the
    round-robin position targeting in the generator actually controls.
    """
    records = [r for r in load_split(lang, split) if r["answer_position"] >= 0]
    by_template: dict[int, list[int]] = {}
    for record in records:
        by_template.setdefault(record["template"], []).append(record["answer_position"])

    for template, positions in sorted(by_template.items()):
        observed = sorted(set(positions))
        ceiling = 1.0 / len(observed) + 0.10
        for position in observed:
            share = positions.count(position) / len(positions)
            assert share <= ceiling, (
                f"{split}/T{template}: position {position} holds the answer {share:.1%} "
                f"of the time across reachable positions {observed} (ceiling {ceiling:.1%})"
            )


@pytest.mark.parametrize("lang", LANGS)
@pytest.mark.parametrize("split", SPLITS)
def test_positional_heuristic_stays_near_chance(lang, split):
    """Assertion 4b: the best always-answer-position-k rule does not score well.

    This is the claim the reported accuracy depends on, stated directly rather
    than inferred from the per-template histograms. The 45% ceiling is set by
    T6: within that family the answer is at position 0 or 1 roughly half the
    time each, so ``test_templates`` -- half T3, half T6 -- tops out in the low
    forties. Every other split lands near 33%. The exact figure per split is
    recorded in ``stats.json``.
    """
    records = [r for r in load_split(lang, split) if r["answer_position"] >= 0]
    best = max(
        sum(1 for r in records if r["answer_position"] == k) / len(records)
        for k in range(3)
    )
    assert best <= 0.45, f"{split}: a fixed-position heuristic scores {best:.1%}"


def pool_side(split: str) -> str:
    """Which side of the entity pools a split draws from."""
    return "test" if split in ("test_names", "test_templates") else "train"


@pytest.mark.parametrize("lang", LANGS)
@pytest.mark.parametrize("split", SPLITS)
def test_no_single_answer_dominates(lang, split):
    """One entity must not be the answer far more often than its peers.

    Two things make the naive "no name exceeds 1.5x uniform" version of this
    test wrong, and both are worth stating because both are easy to get wrong
    again:

    **The comparison group is the gender group, not the pool.** Hindi objects
    are 8 feminine and 6 masculine, and an example picks a gender group before
    it picks names -- so a masculine object is legitimately the answer 8/6 as
    often as a feminine one. Only names drawn from the same group compete with
    each other, so that is where the expectation comes from.

    **The tolerance has to scale with the sample.** Expected counts here range
    from about 15 (a pool inside a 1,000-example test slice) to about 500 (the
    20,000-example training set). At an expected count of 15 the standard
    deviation is nearly 4, so a fixed multiplier that is generous at n=500 is
    guaranteed to fire at n=15 -- and the test takes a *maximum* over roughly
    400 name-cells, whose maximum sits two to three standard deviations out by
    construction. ``expected + 5 * sqrt(expected)`` is a Poisson tail bound
    that tightens as the sample grows.

    Five sigma rather than four because the statistical power lives in the
    training split, not in the slices. On 20,000 examples the bound is about
    1.2x the expected count, so a systematic bias is caught easily; on a
    1,000-example slice it is about 2x, which is honest -- a 20% bias simply
    is not detectable from 175 samples, and a tighter bound there would only
    buy false failures on ordinary noise.

    What this catches is one name being systematically over-represented. It
    would not catch a small bias spread evenly over many names -- that would
    need a goodness-of-fit test, and it is not a failure mode this generator
    has a mechanism for.
    """
    spec = language_spec(lang)
    side = pool_side(split)

    groups: dict[tuple[str, str], dict[str, int]] = {}
    for record in load_split(lang, split):
        if record["answer_position"] < 0:
            continue
        key = (record["dim_pool"], record["gender"])
        counts = groups.setdefault(key, {})
        counts[record["answer"]] = counts.get(record["answer"], 0) + 1

    for (pool, gender), counts in sorted(groups.items()):
        group_size = len(spec.pools[side][pool][gender])
        expected = sum(counts.values()) / group_size
        limit = expected + 5.0 * math.sqrt(expected)
        worst = max(counts, key=lambda name: counts[name])
        assert counts[worst] <= limit, (
            f"{split}/{pool}/{gender}: {worst!r} is the answer {counts[worst]} times "
            f"against an expected {expected:.1f} for one of {group_size} names "
            f"(limit {limit:.1f})"
        )


@pytest.mark.parametrize("lang", LANGS)
def test_both_question_directions_appear(lang):
    """The 'bigger' and 'smaller' phrasings are both well represented.

    If they were not, the model could ignore the adjective in the question and
    still be right most of the time.
    """
    records = load_split(lang, "train")
    asks = [r["ask"] for r in records if r["ask"] in ("big", "small")]
    share = asks.count("big") / len(asks)
    assert 0.35 <= share <= 0.65, f"'big' questions are {share:.1%} of the training set"


@pytest.mark.parametrize("lang", LANGS)
def test_equality_family_is_present_but_not_dominant(lang):
    """The 'neither, they are equal' family sits in the planned 10-15% band."""
    records = load_split(lang, "train")
    share = sum(1 for r in records if r["template"] == 5) / len(records)
    assert 0.08 <= share <= 0.18, f"equality examples are {share:.1%} of the training set"


# --------------------------------------------------------------------------- #
# 5 and 7. Tokenizer properties
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("lang", LANGS)
def test_corpus_is_unk_free_and_within_the_length_cap(lang):
    """Assertions 5 and 7: nothing encodes to <unk>, nothing exceeds the cap.

    The ``+ 1`` is the ``</s>`` that finetuning appends, so the number checked
    here is the length the training loop will actually see.
    """
    sp = load_tokenizer_or_skip(lang)
    unk_id = sp.unk_id()

    for split in SPLITS:
        for record in load_split(lang, split):
            ids = sp.encode(record["prompt"] + " " + record["answer"], out_type=int)
            assert unk_id not in ids, f"{record['id']} contains <unk>: {record['prompt']}"
            assert len(ids) + 1 <= MAX_LEN, f"{record['id']} encodes to {len(ids) + 1} tokens"


# --------------------------------------------------------------------------- #
# 6. Record structure
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("lang", LANGS)
def test_record_structure_is_consistent(lang):
    """Assertion 6, plus the invariants the evaluator and Task 2 rely on."""
    spec = language_spec(lang)
    for split in SPLITS:
        for record in load_split(lang, split):
            meta = TEMPLATES[record["template"]]
            assert record["candidates"][record["answer_index"]] == record["answer"]
            assert len(record["entities"]) == meta["n_entities"] == record["n_entities"]
            assert len(set(record["entities"])) == meta["n_entities"]

            if meta["answer_is_entity"]:
                assert record["answer"] in record["entities"]
                assert record["entities"][record["answer_position"]] == record["answer"]
                assert record["candidates"] == record["entities"]
            else:
                assert record["answer"] == spec.grammar.equal_word
                assert record["answer_position"] == -1
                assert record["candidates"] == record["entities"] + [spec.grammar.equal_word]

            # Mention order must be the order the entities appear in the text.
            positions = [record["prompt"].index(name) for name in record["entities"]]
            assert positions == sorted(positions)
            assert record["prompt"].endswith("?")


# --------------------------------------------------------------------------- #
# 8. Reproducibility
# --------------------------------------------------------------------------- #


def _generate_into(tmp_path: Path, lang: str, seed: int) -> dict[str, bytes]:
    """Run the generator into a temporary directory and return the raw files."""
    out_dir = tmp_path / f"{lang}-{seed}"
    result = subprocess.run(
        [sys.executable, "-m", "finetune.gen_reasoning",
         "--lang", lang, "--out-dir", str(out_dir), "--repo-root", str(REPO_ROOT),
         "--n-train", "300", "--n-val", "60", "--n-test", "60",
         "--seed", str(seed), "--digits", "ascii", "--no-tokenizer"],
        cwd=REPO_ROOT, capture_output=True, text=True,
        # The child prints Devanagari. Without an explicit codec, text=True
        # decodes with the locale default (cp1252 on Windows) and the reader
        # thread dies on the first Devanagari byte.
        encoding="utf-8", errors="replace",
    )
    assert result.returncode == 0, result.stdout + result.stderr
    return {p.name: p.read_bytes() for p in sorted(out_dir.iterdir())}


@pytest.mark.parametrize("lang", LANGS)
def test_generation_is_reproducible(tmp_path, lang):
    """Assertion 8: the same seed produces byte-identical files.

    Run with ``--no-tokenizer`` so the check does not depend on the Phase 1
    artifacts being present, and with an explicit digit script so it does not
    read ``train.bin``.
    """
    first = _generate_into(tmp_path, lang, 4242)
    second = _generate_into(tmp_path / "again", lang, 4242)
    assert sorted(first) == sorted(second)
    for name in sorted(first):
        assert first[name] == second[name], f"{name} differs between two identical runs"


@pytest.mark.parametrize("lang", LANGS)
def test_a_different_seed_produces_different_data(tmp_path, lang):
    """The control for the test above: seeding must actually do something."""
    first = _generate_into(tmp_path, lang, 4242)
    other = _generate_into(tmp_path / "other", lang, 99)
    assert first["train.jsonl"] != other["train.jsonl"]


# --------------------------------------------------------------------------- #
# 9. The labels are correct
# --------------------------------------------------------------------------- #


def rederive_answer(record: dict, equal_word: str) -> str:
    """Work out the correct answer from the record's stated ground truth.

    Deliberately independent of :func:`finetune.gen_reasoning.sample_example`:
    it reads ``order`` (entities from greatest to least) or ``values``, applies
    the semantics of the template family, and returns what the answer must be.
    If the generator ever mislabels an example, this disagrees.

    Args:
        record: One dataset record.
        equal_word: The language's word for "equal".

    Returns:
        The answer the record should carry.
    """
    template = record["template"]
    ask = record["ask"]

    if template == 5:
        values = record["values"]
        assert len(set(values.values())) == 1, "the equality family must have equal values"
        return equal_word

    if template == 4:
        values = record["values"]
        chooser = max if ask == "big" else min
        return chooser(sorted(values), key=lambda name: values[name])

    order = record["order"]  # greatest -> least
    if template == 6:
        return order[1]
    if template == 3:
        pair = record["pair"]
        ranked = [name for name in order if name in pair]
        return ranked[0] if ask == "big" else ranked[-1]
    # T0, T1, T2: pick a pole of the full ordering.
    return order[0] if ask == "big" else order[-1]


@pytest.mark.parametrize("lang", LANGS)
def test_labels_are_correct(lang):
    """Assertion 9: every answer is re-derivable from the stated ground truth."""
    equal_word = language_spec(lang).grammar.equal_word
    for split in SPLITS:
        for record in load_split(lang, split):
            expected = rederive_answer(record, equal_word)
            assert record["answer"] == expected, (
                f"{record['id']} (T{record['template']}, ask={record['ask']}) "
                f"is labelled {record['answer']!r} but should be {expected!r}: "
                f"{record['prompt']}"
            )


@pytest.mark.parametrize("lang", LANGS)
def test_numeric_values_are_well_separated(lang):
    """Comparisons must not hinge on a difference the model cannot resolve."""
    for split in SPLITS:
        for record in load_split(lang, split):
            if record["template"] != 4:
                continue
            values = sorted(record["values"].values())
            gaps = [b - a for a, b in zip(values, values[1:])]
            assert min(gaps) >= 3, f"{record['id']} has values {values}"


@pytest.mark.parametrize("lang", LANGS)
def test_chain_premises_do_not_state_the_asked_pair_directly(lang):
    """T3 must require transitivity, not just reading a premise back.

    The asked pair is the two *non-adjacent* entities of the chain, so no single
    premise relates them. If the pair were ever adjacent, the family would be a
    lookup rather than a reasoning step.
    """
    for record in load_split(lang, "test_templates"):
        if record["template"] != 3:
            continue
        order = record["order"]
        assert set(record["pair"]) == {order[0], order[-1]}
        assert abs(order.index(record["pair"][0]) - order.index(record["pair"][1])) > 1
